### PR TITLE
add extra method info for 'preview'

### PR DESCRIPTION
**Pull request by nclundsten**
This adds extra information for scratch/preview.

**note:** PHP 5.4.3 or newer required for some of the reflection methods (param default value constant) This shouldn't be an issue as 5.6 is the oldest supported PHP version

requires the config setting "completeopt += preview"
example: `set completeopt=longest,menuone,preview`

**preview**
```
public MyNamespace\MyClass->someMethod(
    SomeNamespace\SomeClass $someClass,
    $foo = 'bar'
) : AnotherNamespace\ReturnTypehint

/**
 * Docblock here
 */
```

### CODE REVIEW

**Comment by nclundsten** [comment]
This adds extra information for scratch/preview.

requires the config setting "completeopt += preview"
example: `set completeopt=longest,menuone,preview`

```
public MyNamespace\MyClass->someMethod(
    SomeNamespace\SomeClass $someClass,
    $foo = 'bar'
) : AnotherNamespace\ReturnTypehint

/**
 * Docblock here
 */
```

**Comment by lvht** [comment]
you can type <kbd>Shift</kbd>+<kbd>k</kbd> to show method's declaration under current cursor.

**Comment by lvht** [comment]
phpcd will display the visibility of member in the list like
image

**Comment by lvht** [comment]
phpcd can understand `->` and `::`, if you type `->`, phpcd will only display non static variables and methods, and if `::`, static variables and methods. So it seems no need to display this information in the preview window again.

**Comment by lvht** [comment]
The last information you want but phpcd not display is the return type. However, it is needless again. Because phpcd can understand the method call chain. For example,
```php
<?php
$a = foo(); // function foo has return type of Bar
$a-> // here, phpcd will display Bar's variables and methods

$a = foo()->bar(); // foo has return type A, a has method bar and baz return B
$a-> // here, phpcd will display B's variables and methods
```

**Comment by nclundsten** [comment]
Will modify to show only the things not already given in the list then. Still adds plenty of value.

**Comment by Xerkus** [comment]
I discussed those changes at length with @nclundsten and endorse them.
Extra info is useful in a way that last completion variant stays in preview window when completion menu is already closed and since i use deoplete, I find it more convenient than preview source with `shift-k`.

**Pull request merged**
